name: issue_to_notion_card
on:
  issues:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notion Card Creator
        uses: hongsw/issue-to-notion@v1.1.5
        env:
          NOTION_TOKEN: ${{ secrets.I2N_NOTION_TOKEN }}
          DATABASE_URL: ${{ secrets.I2N_DATABASE_URL }}
          PROPERTY_NAME : status
          PART_PROPERTY_NAME : ${{ secrets.I2N_PART_PROPERTY_NAME }}
          PART_NAME : ${{ secrets.I2N_PART_NAME }}
          STATE_OPEN : ${{ secrets.I2N_STATE_OPEN }}
          STATE_CLOSED : ${{ secrets.I2N_STATE_CLOSED }}
